### ISSUE TITLE
ReportEngine client is failing to validate SSL certificates

### ISSUE THREAD

**Issue by lzoubek** [reportengine/report-engine#1]
Hi, mi report engine client fails to start, and what is worse, it does not catch exception so, no tests can run when it is enabled.

```
[ant:testng] Exception in thread "main" javax.net.ssl.SSLPeerUnverifiedException: peer not authenticated
[ant:testng]    at sun.security.ssl.SSLSessionImpl.getPeerCertificates(SSLSessionImpl.java:371)
[ant:testng]    at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:128)
[ant:testng]    at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:397)
[ant:testng]    at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:148)
[ant:testng]    at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:149)
[ant:testng]    at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:121)
[ant:testng]    at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:573)
[ant:testng]    at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:425)
[ant:testng]    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:820)
[ant:testng]    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:754)
[ant:testng]    at org.jboss.resteasy.client.core.executors.ApacheHttpClient4Executor.execute(ApacheHttpClient4Executor.java:182)
[ant:testng]    at org.jboss.resteasy.core.interception.ClientExecutionContextImpl.proceed(ClientExecutionContextImpl.java:39)
[ant:testng]    at org.jboss.resteasy.plugins.interceptors.encoding.AcceptEncodingGZIPInterceptor.execute(AcceptEncodingGZIPInterceptor.java:40)
[ant:testng]    at org.jboss.resteasy.core.interception.ClientExecutionContextImpl.proceed(ClientExecutionContextImpl.java:45)
[ant:testng]    at org.jboss.resteasy.client.ClientRequest.execute(ClientRequest.java:443)
[ant:testng]    at org.jboss.resteasy.client.ClientRequest.httpMethod(ClientRequest.java:677)
[ant:testng]    at org.jboss.resteasy.client.ClientRequest.get(ClientRequest.java:479)
[ant:testng]    at org.jboss.resteasy.client.ClientRequest.get(ClientRequest.java:508)
[ant:testng]    at com.redhat.reportengine.client.RESTClientRestEasy.get(RESTClientRestEasy.java:54)
[ant:testng]    at com.redhat.reportengine.client.RemoteAPI.insertTestSuite(RemoteAPI.java:190)
[ant:testng]    at com.redhat.reportengine.client.RemoteAPI.doInitialize(RemoteAPI.java:177)
[ant:testng]    at com.redhat.reportengine.client.RemoteAPI.initClient(RemoteAPI.java:148)
[ant:testng]    at com.redhat.reportengine.client.RemoteAPI.initClient(RemoteAPI.java:144)
[ant:testng]    at com.redhat.reportengine.client.ReportEngineTestNGListner.<init>(ReportEngineTestNGListner.java:26)
[ant:testng]    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[ant:testng]    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
[ant:testng]    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[ant:testng]    at java.lang.reflect.Constructor.newInstance(Constructor.java:532)
[ant:testng]    at java.lang.Class.newInstance0(Class.java:372)
[ant:testng]    at java.lang.Class.newInstance(Class.java:325)
[ant:testng]    at org.testng.internal.ClassHelper.newInstance(ClassHelper.java:49)
[ant:testng]    at org.testng.TestNG.initializeConfiguration(TestNG.java:906)
[ant:testng]    at org.testng.TestNG.run(TestNG.java:1005)
[ant:testng]    at org.testng.TestNG.privateMain(TestNG.java:1338)
[ant:testng]    at org.testng.TestNG.main(TestNG.java:1307)
[ant:testng] The tests failed.
```

**Comment by jkandasa** [comment]
Libor,

If we use Self Signed Certificate in our Report Engine server we will face this issue. To overcome this issue please follow the document https://github.com/jkandasa/resource/wiki/Adding-a-Certificate-into-the-Java-Certificate-Store

Thanks,
-Jeeva

**Comment by lzoubek** [comment]
Thanks for response, but I don't get it. 

Does  that mean I need to import this certificate on each host I am running automation with report engine client enabled?

**Comment by jkandasa** [comment]
Libor, Yes. you have to import on each host where you are running automation with this report engine client enabled. This is one time setup, however if we update jdk/jre (or) if we change report engine server self-signed certificate, we have to do it again.

**Comment by lzoubek** [comment]
This is not acceptable. 
1. testNGListener should never prevent running tests - which now happens, when there is this "security" issue, exception is uncaught
2. why is https required for transfering test resutls? Is this confidential data? I guess test results are not.
3. whole idea of SSL (client having server certificate in trusted store) is besides others avoid man-in-the-middle attack. Your workaround does not avoid it at all, because of the way you get the certificate from server (by downloading it directly, you already trust the server)
4. In dev/qa environment I haven't seen SSL certs signed by trusted authority - this is consts $
5. you cannot force your users to do manual steps before using report engine clients especially integration tests or CI - testing usually happens on different host or in cloud (new host, that is destroyed right after it executes testsuite)

I hope all this is reasonable to get this work same way as it worked when transporting using RMI (or similar).

Thanks

**Comment by jkandasa** [comment]
Libor,

Thank you!! Now rest API's are accessible via both http/https and login page alone strictly in https and if something goes wrong in report engine java client will not block the complete test suite.
